deluge-torrent/deluge

- deluge/tests/test_ui_entry.py
- deluge/ui/baseargparser.py
Command line arguments like "-L info" were incorrectly
identified as console subcommands which caused parsing
to fail.
> [Console] Fix bug when parsing UI commands

- deluge/tests/test_ui_entry.py
- deluge/ui/baseargparser.py
- deluge/ui/console/console.py
- deluge/ui/console/main.py
- deluge/ui/ui.py
- deluge/ui/ui_entry.py
When starting console with './deluge-console', providing
loggin level '-L info' would fail to parse as it identified
'info' as a subcommand.
> [Console] Fix to console argument parsing

- deluge/core/preferencesmanager.py
- deluge/ui/console/modes/preference_panes.py
- deluge/ui/gtkui/addtorrentdialog.py
- deluge/ui/gtkui/glade/preferences_dialog.ui
- deluge/ui/gtkui/options_tab.py
- deluge/ui/gtkui/path_combo_chooser.py
- deluge/ui/gtkui/preferences.py
- deluge/ui/gtkui/torrentview.py
There is an discussion for these changes in PR #8 
* [#2133](http://dev.deluge-torrent.org/ticket/2133) Add flags for port reuse and disable binding to system port.
* [#2122](http://dev.deluge-torrent.org/ticket/2122) For random port, use single port and store it for reuse.
* [#2343](http://dev.deluge-torrent.org/ticket/2343) Fix 'Invalid Arg' from listen_on, likely due to whitespace as interface value.
* Consolidate listen_on and outgoing_port into single '__set...' methods.
ToDo:
> Setting listening ports fixes and updates

- DEPENDS
- deluge/core/core.py
- deluge/core/preferencesmanager.py
- deluge/core/torrent.py
- deluge/ui/gtkui/peers_tab.py
* libtorrent >= 1.1 dropped support for GeoIP so this add support
using MaxMind GeoIP Legacy Python Extension API.
* It is known by the following package names:
* Maxmind: geoip-api-python
* Linux: python-geoip
* PyPi: GeoIP
> [#2861] [Core] Add support for python-geoip

- deluge/common.py
- deluge/log.py
- deluge/tests/test_common.py
- deluge/ui/gtkui/details_tab.py
- deluge/ui/gtkui/files_tab.py
- deluge/ui/gtkui/glade/main_window.tabs.ui
- deluge/ui/gtkui/listview.py
- deluge/ui/gtkui/mainwindow.py
- deluge/ui/gtkui/peers_tab.py
- deluge/ui/gtkui/status_tab.py
- deluge/ui/gtkui/statusbar.py
- deluge/ui/gtkui/systemtray.py
- deluge/ui/gtkui/torrentview_data_funcs.py
This is a work in progress so no cleaned up commits yet...
It is an attempt to regain valuable screen space in areas such as columns, indicators, statusbars by shorting the displayed text for values and units.
Issues:
> Use less versbose units in UI's to gain space and cleaner look

- deluge/ui/web/js/deluge-all/preferences/NetworkPage.js
- deluge/ui/web/js/deluge-all/preferences/PreferencesWindow.js
Convert to a single port in WebUI preferences.
Issues:
> [#2133] [WebUI] Modify UI to display single incoming port

- deluge/core/alertmanager.py
- deluge/core/core.py
- deluge/core/preferencesmanager.py
- deluge/core/torrent.py
- deluge/core/torrentmanager.py
- deluge/plugins/Scheduler/deluge/plugins/scheduler/core.py
- deluge/ui/console/modes/preferences/preference_panes.py
- deluge/ui/gtkui/files_tab.py
- deluge/ui/gtkui/glade/preferences_dialog.ui
- deluge/ui/gtkui/options_tab.py
- deluge/ui/gtkui/preferences.py
- deluge/ui/web/js/deluge-all/preferences/NetworkPage.js
This is a refactor that works with both 1.0 and 1.1 (with/without deprecated) libtorrent branches. It is designed to try non-deprecated and fallback to deprecated with the aim to make it trivial to remove the code in future.
I am keeping compatibility for now to ease testing (I still use 1.0.9 for dev...) but likely will remove support for 1.0 and 1.1 deprecated methods shortly before release.
Still to be done:
> Feature/fixup lt1.1 deprecated

- deluge/core/daemon.py
- deluge/plugins/Stats/deluge/plugins/stats/tests/test_stats.py
- deluge/ui/client.py
- deluge/ui/gtkui/aboutdialog.py
- deluge/ui/gtkui/glade/preferences_dialog.ui
- deluge/ui/gtkui/gtkui.py
- deluge/ui/gtkui/mainwindow.py
- deluge/ui/gtkui/menubar.py
- deluge/ui/gtkui/menubar_osx.py
- deluge/ui/gtkui/new_release_dialog.py
- deluge/ui/gtkui/preferences.py
- deluge/ui/gtkui/queuedtorrents.py
- deluge/ui/gtkui/systemtray.py
- deluge/ui/gtkui/toolbar.py
- deluge/ui/web/json_api.py
The term `classic` is rather confusing so replace with `standalone`.
> Rename classic to standalone in all code

- deluge/core/core.py
- deluge/core/torrent.py
- deluge/decorators.py
- deluge/ui/client.py
- deluge/ui/console/modes/torrentdetail.py
- deluge/ui/gtkui/files_tab.py
- deluge/ui/gtkui/menubar.py
- deluge/ui/gtkui/options_tab.py
- deluge/ui/web/js/deluge-all/details/FilesTab.js
- deluge/ui/web/js/deluge-all/details/OptionsTab.js
> [#495] Deprecate core.set_torrent_* for core.set_torrent_options

- deluge/core/torrent.py
* The default piece priority was changed in lt 1.1 from 1 to 4
so in 1.3 we will simple convert them back to 1 as 4 is not used.
* The set_file_priorities method was refactored to make the changes simpler.
* Also include correction for get_files() so it returns an empty
list not 0.0 if no torrent_info is available.
> [#2946] Workaround 1.1 libtorrent default piece priority

- ChangeLog
- deluge/core/core.py
- deluge/core/daemon.py
- deluge/core/daemon_entry.py
- deluge/core/preferencesmanager.py
- deluge/ui/console/modes/preferences/preference_panes.py
- deluge/ui/gtkui/glade/preferences_dialog.ui
- deluge/ui/gtkui/preferences.py
- deluge/ui/web/js/deluge-all/preferences/NetworkPage.js
Currently if you specify -i only the libtorrent listen_interfaces is set.
I believe one of two options should be used:
-i sets listen_interfaces and outgoing_interfaces.
or
-i sets listen_interface and a new -o sets outgoing_interfaces.
Im sure for some reason or another someone would want to use two interfaces so the second option is probably best.
> #3171 Add Option To Specify Outgoing Connection Interface

- deluge/ui/web/common.py
In a previous commit d4023e7dde42 removed a decode for Python 3 but
with translated text returned by gettext encoded on Python 2 the
escape function would raise a UnicodeDecodeError trying to use ascii
to decode.
The fix is to decode the message returned by gettext on Python 2.
> [WebUI] Fix error escaping translated text

- deluge/tests/test_ui_console_fields.py
Curses is not available on Windows so skip AppVeyor test that errors
with:
E       NameError: global name 'curses' is not defined
> [Tests] Fix console test fail on AppVeyor

- deluge/tests/common_web.py
- deluge/tests/test_core.py
- deluge/tests/test_httpdownloader.py
- deluge/tests/test_json_api.py
- deluge/tests/test_webserver.py
- deluge/ui/web/common.py
- deluge/ui/web/json_api.py
- deluge/ui/web/server.py
- setup.cfg
Trac ticket: https://dev.deluge-torrent.org/ticket/3244
Use EncodingResourceWrapper to replace compress function so that the proper checks for accept-encoding header are made
Also ensure only text if compressed and images are uncompressed.
> [#3244] [Web] Add support for accept-encoding header

- ChangeLog
- deluge/core/rpcserver.py
Without this, clients cannot easily verify the full chain of certificates. This is only useful if the automatically generated self signed certificates are replaced with ca signed certificates. This is necessary to prevent man-in-the-middle attacks. While the current Deluge 1.3 client does not support secure connections, other client implementations can.
This is a trivial change that does not affect the current client as far as I have tested and can only help other clients. It would be nice if the official Deluge client supported enforcing trusted signatures but that is a different subject.
----
I have not been able to test Deluge 2.0 to see if the same issue affects it. Looking at the source, it looks like it is using a different SSL library which doesn't have a chain(less) API.
Edit: …
> Allow using certificate chain files for secure SSL connections

- deluge/log.py
Deluge's logger class extends Python's `logging.Logger`. Since Python
3.8, it takes an additional argument `stacklevel`.
The implementation in Deluge does not support that. Instead of working
around the problem by adding the parameter and ignoring it (or copying
code from `logging`), remove the brittle override.
Log messages still seem to work correctly.
> [Logging] Fix Python 3.8 compatibility

- .travis.yml
- docs/source/devguide/tutorials/01-setup.md
- requirements-dev.txt
- requirements-tests.txt
- tox.ini
* Error occurring with Pytest 5.4 so pin to below that version.
* Fix minor issues with Travis config.
* Use full command-switches for pytest in tox config.
> Fix pytest and travis issues

- deluge/config.py
- deluge/tests/test_config.py
If a password or other string contained a double-quote then the config
would fail to be loaded on startup and reset.
This occurred due to fixing a similar issue with curly braces #3079
in commit 33e9545cd44 and the checking for double-quotes had an
unforseen consequence.
To resolve both these issues the code to check for json objects in
config files was simplified and utilises the json module raw_decode
method to ensure the extracted string indexes are json objects.
> [Config] Fix loading config with double-quotes in string

- deluge/tests/test_ui_gtk3.py
- deluge/ui/gtk3/common.py
Comparisons on Python 3 are much stricter resulting in the following
error comparing with None:
TypeError: '>' not supported between instances of 'NoneType' and 'str'
Fix this by getting the type of the other value and getting it's default
value.
> [#3309|GTK] Fix cmp function for None types

- deluge/config.py
- deluge/tests/test_config.py
- deluge/ui/console/cmdline/commands/info.py
- deluge/ui/hostlist.py
- setup.py
Added a new Config class parameter `mask_funcs` to enable config
instances hide sensitive information that would appear in config debug
logs.
> [Config] Add mask_funcs to help mask passwords in logs

- packaging/win/delugewin.spec
- setup.py
Fixed a mistake settings entry points in setup.py. Replaced with simpler
logic since gui_scripts only affect Windows.
Fixed entry point changes affecting pyinstaller build
Corrected deluge-web.exe to have no console instead of
deluge-web-debug.exe
> [Build] Fix entry point build errors

- deluge/ui/web/js/deluge-all/Deluge.js
- deluge/ui/web/js/deluge-all/EditTrackersWindow.js
- deluge/ui/web/js/deluge-all/FilterPanel.js
- deluge/ui/web/js/deluge-all/Formatters.js
- deluge/ui/web/js/deluge-all/TorrentGrid.js
- deluge/ui/web/js/deluge-all/add/AddWindow.js
- deluge/ui/web/js/deluge-all/add/FilesTab.js
- deluge/ui/web/js/deluge-all/details/DetailsTab.js
- deluge/ui/web/js/deluge-all/details/FilesTab.js
- deluge/ui/web/js/deluge-all/details/PeersTab.js
- deluge/ui/web/js/deluge-all/preferences/PreferencesWindow.js
- deluge/ui/web/json_api.py
[[WebUI] Fix encoding HTML entities for torrent attributes](https://github.com/deluge-torrent/deluge/pull/375/commits/a5503c0c606e196f368a58ea3d1b8457e76a3a31)
Ensure all torrent attributes that might contain malicious HTML entities
are encoded.
By allowing HTML entities to be rendered it enable malicious torrent
files to perform XSS attacks.
Resolves: https://dev.deluge-torrent.org/ticket/3459
[[WebUI] Move HTML entity encoding to client](https://github.com/deluge-torrent/deluge/pull/375/commits/8ece036770484e170d5a728cdb25062088068f71)
We should not be mangling the torrent data in the JSON API since this
can have unintended consquences with names and filepaths that can be
edited. If we escape those symbols in the JSON API then the data no
longer matches that stored by core. Therefore …
> [WebUI] Move HTML entity encoding to client
